# Generated by Django 4.1.3 on 2022-11-29 01:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_full', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='客户全称')),
                ('name_simple', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='客户简称')),
                ('department', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='部门')),
                ('country', models.CharField(blank=True, max_length=256, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=256, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=256, null=True, verbose_name='城市')),
                ('customer_type', models.CharField(blank=True, choices=[('pcb_factory', '板厂'), ('design_customer', '设计端客户')], default='pcb_factory', max_length=20, null=True, verbose_name='客户类型')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='备注')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
