# Generated by Django 4.1.3 on 2022-11-29 06:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_job_job_name', models.CharField(blank=True, help_text='此用户筛选条件记录用的', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='筛选-料号名')),
                ('query_job_author', models.CharField(blank=True, help_text='此用户筛选条件记录用的', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='筛选-负责人')),
                ('query_job_from_object_pcb_factory', models.CharField(blank=True, help_text='此用户筛选条件记录用的', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='筛选-料号来源-板厂')),
                ('query_job_paginator_page', models.IntegerField(blank=True, default=10, help_text='每页显示行数', null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(5)], verbose_name='query_job_paginator_page')),
                ('query_job_status', models.CharField(blank=True, choices=[('all', '所有'), ('draft', '草稿'), ('published', '正式')], default='all', help_text='此用户筛选条件记录用的', max_length=20, null=True, verbose_name='筛选-状态')),
                ('remark', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='备注')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_query_data_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'account_query_data',
                'ordering': ('-publish',),
            },
        ),
    ]
