# Generated by Django 4.1.3 on 2022-11-30 07:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0007_mytagforeptest'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0012_jobinfofordevtest_author_jobinfofordevtest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedWhateverForEptest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.mytagforeptest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobFoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='整理过的测试料号，包括：Gerber为rar压缩包；ODB++为tgz压缩包；DXF为单个文件；PCB为单个文件；', null=True, upload_to='files', verbose_name='测试料号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '正式')], default='draft', help_text='草稿表示未经人工确认', max_length=10, verbose_name='状态')),
                ('publish', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='发布时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, help_text='说明备注', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='备注')),
                ('author', models.ForeignKey(blank=True, help_text='负责人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eptest_job_for_test_user', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eptest_job_for_test_job_job', to='job.job', verbose_name='料号名称')),
                ('tags', taggit.managers.TaggableManager(help_text='必填', through='eptest.TaggedWhateverForEptest', to='taggit.MyTagForEptest', verbose_name='Tags')),
            ],
            options={
                'db_table': 'eptest_job_for_test',
                'ordering': ('-create_time',),
            },
        ),
    ]
