# Generated by Django 4.1.3 on 2022-11-30 07:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0012_jobinfofordevtest_author_jobinfofordevtest_status'),
        ('taggit', '0007_mytagforeptest'),
        ('eptest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobFoTest',
            new_name='JobForTest',
        ),
    ]
