# Generated by Django 4.1.3 on 2022-11-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eptest', '0004_rename_genre_epcammodule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EpcamModule',
            new_name='EpcamModule2',
        ),
    ]
