# Generated by Django 4.1.3 on 2022-11-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eptest', '0005_rename_epcammodule_epcammodule2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EpcamModule2',
            new_name='EpcamModule',
        ),
        migrations.AlterModelTable(
            name='epcammodule',
            table='eptest_epcam_module',
        ),
    ]
