# Generated by Django 4.1.3 on 2022-11-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eptest', '0006_rename_epcammodule2_epcammodule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epcammodule',
            options={'ordering': ('id',)},
        ),
    ]
