# Generated by Django 4.1.3 on 2022-11-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eptest', '0007_alter_epcammodule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epcammodule',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
