# Generated by Django 4.1.3 on 2022-11-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eptest', '0008_alter_epcammodule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfortest',
            name='test_usage_for_epcam_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eptest_job_for_test_epcam_module', to='eptest.epcammodule', verbose_name='模块名称'),
        ),
    ]
