# Generated by Django 4.1.3 on 2022-11-30 08:08

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eptest', '0009_jobfortest_test_usage_for_epcam_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfortest',
            name='test_usage_for_epcam_module',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eptest_job_for_test_epcam_module', to='eptest.epcammodule', verbose_name='模块名称'),
        ),
    ]
