# Generated by Django 4.1.3 on 2022-11-30 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eptest', '0010_alter_jobfortest_test_usage_for_epcam_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfortest',
            name='bool_layer_info',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], default='false', help_text='不需要人工填写,系统用', max_length=10, null=True, verbose_name='是否有层别信息'),
        ),
        migrations.AddField(
            model_name='jobfortest',
            name='bug_info',
            field=models.CharField(blank=True, help_text='Bug信息', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='Bug信息'),
        ),
        migrations.AddField(
            model_name='jobfortest',
            name='standard_odb',
            field=models.FileField(blank=True, help_text='标准料号，用来测试比对用的', null=True, upload_to='files', verbose_name='标准料号'),
        ),
        migrations.AddField(
            model_name='jobfortest',
            name='vs_result_ep',
            field=models.CharField(choices=[('passed', '成功'), ('failed', '失败'), ('none', '未比对')], default='none', help_text='导入测试管理员负责填写', max_length=10, verbose_name='悦谱比图结果'),
        ),
        migrations.AddField(
            model_name='jobfortest',
            name='vs_result_g',
            field=models.CharField(choices=[('passed', '成功'), ('failed', '失败'), ('none', '未比对')], default='none', help_text='导入测试管理员负责填写', max_length=10, verbose_name='G软件比图结果'),
        ),
        migrations.AddField(
            model_name='jobfortest',
            name='vs_time_ep',
            field=models.CharField(blank=True, help_text='系统生成', max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='悦谱比对时间戳'),
        ),
        migrations.AddField(
            model_name='jobfortest',
            name='vs_time_g',
            field=models.CharField(blank=True, help_text='系统生成', max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='G比对时间戳'),
        ),
    ]
