"""
Django settings for epdms project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path







# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-en5)(qk*1p7r(lpjc7*v!4d_3$%m0xe4%x!5^ci%x94(%09g!v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']
#


SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'account.apps.AccountConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'back_stage.apps.BackStageConfig',
    'taggit',
    'job.apps.JobConfig',
    'multiselectfield',
    'mptt',
    'eptest.apps.EptestConfig',
    'zentao.apps.ZentaoConfig',
    'django.contrib.sites',
    'import_export',
    'rest_framework',#vue用
    'corsheaders',# 跨域
    'django_filters',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',#vue用
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'epdms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'epdms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'epdms',
        # 'NAME': 'ep_develop',
        'USER': 'postgres',
        'PASSWORD': 'cc',
        # 'HOST': '10.97.80.118',
        'HOST': '127.0.0.1',
        # 'HOST': '10.97.80.147',

        'PORT': '5432',
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-Hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# 当运行 python manage.py collectstatic 的时候
# STATIC_ROOT 文件夹 是用来将所有STATICFILES_DIRS中所有文件夹中的文件，以及各app中static中的文件都复制过来
# 把这些文件放到一起是为了用apache等部署的时候更方便
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')

# 其它 存放静态文件的文件夹，可以用来存放项目中公用的静态文件，里面不能包含 STATIC_ROOT
# 如果不想用 STATICFILES_DIRS 可以不用，都放在 app 里的 static 中也可以
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "common_static"),
    #'/path/to/others/static/',  # 用不到的时候可以不写这一行
)

# 这个是默认设置，Django 默认会在 STATICFILES_DIRS中的文件夹 和 各app下的static文件夹中找文件
# 注意有先后顺序，找到了就不再继续找了
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder"
)




# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#下面用的465端口，阿里云可以用的
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'chen320821@163.com' # 帐号
# EMAIL_HOST_PASSWORD =  'angela123.163'  # 密码
EMAIL_HOST_PASSWORD =  'CZZLYIRGEDHOTHWA'  # 密码
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# 如果没有指定next参数，登录成功后重定向的URL
LOGIN_REDIRECT_URL = 'dashboard'
# 用户需要登录的情况下被重定向到的URL地址（例如@login_required重定向到的地址）
LOGIN_URL = 'login'
# 用户需要登出的时候被重定向到的URL地址
LOGOUT_URL = 'logout'



# 由于我们要允许用户上传图片，必须配置Django让其提供媒体文件服务，在settings.py中加入下列内容：
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# <---------------------------------------------------simpleui--------------------------------------------------------->
# 隐藏simpleui主页信息
SIMPLEUI_HOME_INFO = False

# 自定义SIMPLEUI的Logo
# SIMPLEUI_LOGO = 'https://avatars2.githubusercontent.com/u/13655483?s=60&v=4'
# simpleui修改logo
# 如果需要使用本地图片，需要在Lib/site-packages/simpleui/static/admin/simpleui-x/img中把原来的logo.png替换掉（图片名称不要改变）。


# 设置默认主题
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'







# 修改默认首页
# SIMPLEUI_HOME_PAGE = 'http://127.0.0.1:8000/back_stage/'
SIMPLEUI_HOME_PAGE = '../back_stage/'
SIMPLEUI_HOME_TITLE = '看板'
SIMPLEUI_HOME_ICON = 'fa-solid fa-gauge'


# 设置simpleui 点击首页图标跳转的地址；首页顶部首页图标默认跳转地址为/，即根目录；
# SIMPLEUI_INDEX = 'https://www.88cto.com'









# 'http://127.0.0.1:8000/admin/#/admin/job/job/'
SIMPLEUI_CONFIG = {
    #system_keep 保留系统菜单,该字段用于告诉simpleui，是否需要保留系统默认的菜单，默认为False，不保留。 如果改为True，自定义和系统菜单将会并存
    'system_keep': True,
    # menu_display过滤显示菜单和排序功能,该字段用于告诉simpleui，是否需要开启过滤显示菜单和排序功能。
    # 默认可以不用填写，缺省配置为默认排序，不对菜单进行过滤和排序。
    # 开启认为传一个列表，如果列表为空，则什么也不显示。列表中的每个元素要对应到menus里面的name字段
    'menu_display': ['主料号管理','测试','用户信息', '权限认证','禅道','站点'],
    #dynamic 开启动态菜单功能,该字段用于告诉simpleui，是否需要开启动态菜单功能。
    # 默认可以不用填写，缺省配置为False，不开启动态菜单功能。开启为True，开启后，每次用户登陆都会刷新左侧菜单配置。
    # 需要注意的是：开启后每次访问admin都会重读配置文件，所以会带来额外的消耗。
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    # menus,如果SIMPLEUI_CONFIG中存在menus字段，将会覆盖系统默认菜单。并且menus中输出的菜单不会受权限控制。
    'menus':
        [
            {
                'app': 'job',
                'name': '主料号管理',
                'icon': 'fa-solid fa-list',
                'models': [
                    {
                        'name': '主料号管理',
                        'icon': 'fa-solid fa-list',
                        'url': '/admin/job/job/'
                    },
                    {
                        'name': '研发测试料号',
                        'icon': 'fa-solid fa-laptop-code',
                        'url': '/admin/job/jobinfofordevtest/'
                    }
                ]
            },

            {
                'app': 'eptest',
                'name': '测试',
                'icon': 'fa-solid fa-microscope',
                'models': [
                    {
                        'name': '测试料号管理',
                        'icon': 'fa-solid fa-list',
                        'url': '/admin/eptest/jobfortest/'
                    },
                    {
                        'name': '层别管理',
                        'icon': 'fa-thin fa-layer-group',
                        'url': '/admin/eptest/layer/'
                    },
                    {
                        'name': 'VS管理',
                        'icon': 'fa-solid fa-code-compare',
                        'url': '/admin/eptest/vs/'
                    },
                    {
                        'name': 'Bug管理',
                        'icon': 'fa-solid fa-bug',
                        'url': '/admin/eptest/bug/'
                    },
                    {
                        'name': '模块管理',
                        'icon': 'fa-solid fa-cube',
                        'url': '/admin/eptest/epcammodule/'
                    }
                ]
            },

            {
                'app': 'account',
                'name': '用户信息',
                'icon': 'fa-regular fa-user',
                'models': [
                    {
                        'name': '用户信息',
                        'icon': 'fa fa-user',
                        'url': '/admin/account/profile/'
                    },
                    {
                        'name': '客户管理',
                        'icon': 'fa fa-user',
                        'url': '/admin/account/customer/'
                    },

                ]
            },



            {
                'app': 'auth',
                'name': '权限认证',
                'icon': 'fas fa-user-shield',
                'models':
                    [
                        {
                            'name': '组',
                            'icon': 'fa fa-user',
                            'url': 'auth/group/'
                        },
                        {
                            'name': '用户',
                            'icon': 'fa fa-user',
                            'url': 'auth/user/'
                        },
                    ]
            },



            {
                'app': 'zentao',
                'name': '禅道',
                'icon': 'fa-solid fa-bug',
                'models':
                    [
                        {
                            'name': 'Bug',
                            'icon': 'fa-solid fa-bug',
                            'url': '/zentao/BugView'
                        },
                        {
                            'name': 'else',
                            'icon': 'fa-solid fa-bug',
                            'url': 'else'
                        },
                    ]
            },

            {
                'app': '',
                'name': 'test',
                'icon': 'fas fa-user-shield',
                'models':
                    [
                        {
                            'name': 'test1',
                            'icon': 'fa fa-user',
                            'url': 'www.baid.com'
                        },
                        {
                            'name': 'test2',
                            'icon': 'fa fa-user',
                            'url': ''
                        },
                    ]
            },

        ]


}


# <---------------------------------------------------simpleui--------------------------------------------------------->



# vue

# cc
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}



#在Django中使用django-cors-headers库来处理CORS
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

#上述配置将允许来自任何源的跨域请求。如果你只想允许特定的域，请将CORS_ORIGIN_ALLOW_ALL设置为False，并添加你想允许的域的列表，例如：
# CORS_ORIGIN_ALLOW_ALL = False
# CORS_ORIGIN_WHITELIST = [
#     'http://127.0.0.1:5173',
#     'http://example.com',
#     'http://localhost:3000',
#     'http://10.97.80.119:5173',
# ]