# Generated by Django 4.1.3 on 2022-11-28 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(help_text='料号名称,有可能有重复名字', max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='料号名称')),
            ],
        ),
    ]
