# Generated by Django 4.1.3 on 2022-11-28 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_taggedwhatever_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='author',
            field=models.ForeignKey(blank=True, help_text='料号上传人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_jobs', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='job',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='job',
            name='file_compressed',
            field=models.FileField(blank=True, help_text='原始文件,rar压缩包', null=True, upload_to='files', verbose_name='原始文件'),
        ),
        migrations.AddField(
            model_name='job',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '正式')], default='draft', help_text='草稿表示未经人工确认', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
