# Generated by Django 4.1.3 on 2022-11-28 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_author_job_create_time_job_file_compressed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remark',
            field=models.CharField(blank=True, help_text='料号的说明备注', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='备注'),
        ),
    ]
