# Generated by Django 4.1.3 on 2022-11-29 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer'),
        ('job', '0004_job_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='from_object_pcb_design',
            field=models.ForeignKey(blank=True, help_text='料号来源-设计端', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_job_account_customer_pcb_design', to='account.customer', verbose_name='料号来源-设计端'),
        ),
        migrations.AddField(
            model_name='job',
            name='from_object_pcb_factory',
            field=models.ForeignKey(blank=True, help_text='料号来源-板厂', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_job_account_customer_pcb_factory', to='account.customer', verbose_name='料号来源-板厂'),
        ),
    ]
