# Generated by Django 4.1.3 on 2022-11-29 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_from_object_pcb_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cc',
            field=models.CharField(blank=True, help_text='cc', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='cc'),
        ),
    ]
