# Generated by Django 4.1.3 on 2022-11-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_cc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cc',
        ),
    ]
