# Generated by Django 4.1.3 on 2022-11-30 02:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_job_cc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-create_time',)},
        ),
        migrations.AddField(
            model_name='job',
            name='has_file_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('gerber274x', 'Gerber274X'), ('dxf', 'DXF'), ('dwg', 'DWG'), ('odb', 'ODB'), ('pcb', 'PCB')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '正式')], default='draft', help_text='草稿表示未经人工确认', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterModelTable(
            name='job',
            table='job_job',
        ),
    ]
