# Generated by Django 4.1.3 on 2022-11-30 02:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_options_job_has_file_type_alter_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='has_file_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('gerber274x', 'Gerber274X'), ('dxf', 'DXF'), ('dwg', 'DWG'), ('odb', 'ODB'), ('pcb', 'PCB')], max_length=200, null=True, verbose_name='包含文件类型'),
        ),
    ]
