# Generated by Django 4.1.3 on 2022-11-30 03:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_jobinfofordevtest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobinfofordevtest',
            options={'ordering': ('-create_time',)},
        ),
        migrations.AddField(
            model_name='jobinfofordevtest',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='jobinfofordevtest',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='jobinfofordevtest',
            name='remark',
            field=models.CharField(blank=True, help_text='料号的说明备注', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='jobinfofordevtest',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterModelTable(
            name='jobinfofordevtest',
            table='job_job_info_for_dev_test',
        ),
    ]
