# Generated by Django 4.1.3 on 2022-11-30 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0011_alter_jobinfofordevtest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfofordevtest',
            name='author',
            field=models.ForeignKey(blank=True, help_text='负责人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_job_info_for_dev_test_user', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='jobinfofordevtest',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '正式')], default='draft', help_text='草稿表示未经人工确认', max_length=10, verbose_name='状态'),
        ),
    ]
